
################################################################################
#
#  Copyright (c) 2019, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Continuous integration configuration file.
#
#  These references helped:
#  https://docs.travis-ci.com/user/languages/cpp/
#  https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/.travis.yml
#
################################################################################

# We're compiling C++ code.
language: cpp

# For now we're only using this compiler.
compiler: gcc

# This flavor of linux comes with the version of cmake and gcc we need.
# We use the add_compile_definitions command in a CMakeLists.txt file.
# https://cmake.org/cmake/help/v3.12/release/3.12.html
# https://docs.travis-ci.com/user/languages/cpp/
dist: xenial

# We install things so we need sudo.
sudo: required

# Install what we need.
install:
- sudo pip install gcovr
- sudo apt-get --assume-yes install libopenscenegraph-dev

# The sequence of commands that get executed.
script:

- pwd
- echo ${HOME}
- ls

# Set up (most of) the environment.
- export GIT_BRANCH=`git branch | awk '/\*/ { print $2; }'`
- export THIS_PROJECT_DIR=`pwd`
- cd ..
- export EXTERNAL_DIR=`pwd`/external
- mkdir -p ${EXTERNAL_DIR}
- export CATCH2_INC_DIR=${EXTERNAL_DIR}
- export LOCAL_DEV_LIB_DIR=${EXTERNAL_DIR}/local_dev_output
- export LOCAL_DEV_BIN_DIR=${EXTERNAL_DIR}/local_dev_output
- export USUL_LIB_DIR=${LOCAL_DEV_LIB_DIR}
- export USUL_BIN_DIR=${LOCAL_DEV_BIN_DIR}
- export OSG_TOOLS_LIB_DIR=${LOCAL_DEV_LIB_DIR}
- export OSG_TOOLS_BIN_DIR=${LOCAL_DEV_BIN_DIR}

- echo ${GIT_BRANCH}
- echo ${THIS_PROJECT_DIR}
- echo ${EXTERNAL_DIR}
- echo ${CATCH2_INC_DIR}
- echo ${LOCAL_DEV_LIB_DIR}
- echo ${LOCAL_DEV_BIN_DIR}
- echo ${USUL_LIB_DIR}
- echo ${USUL_BIN_DIR}
- echo ${OSG_TOOLS_LIB_DIR}
- echo ${OSG_TOOLS_BIN_DIR}

- ls ${THIS_PROJECT_DIR}
- ls ${EXTERNAL_DIR}
- ls ${CATCH2_INC_DIR}
- ls ${LOCAL_DEV_LIB_DIR}
- ls ${LOCAL_DEV_BIN_DIR}
- ls ${USUL_LIB_DIR}
- ls ${USUL_BIN_DIR}
- ls ${OSG_TOOLS_LIB_DIR}
- ls ${OSG_TOOLS_BIN_DIR}

# Set up Catch2 in the home directory so that gcovr does not analyze it too.
- mkdir -p ${CATCH2_INC_DIR}/catch2
- curl https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp > ${CATCH2_INC_DIR}/catch2/catch.hpp

# Set up Usul in the home directory so that gcovr does not analyze it too.
- cd ${EXTERNAL_DIR}
- git clone https://github.com/perryiv/usul.git
- cd usul
- git checkout ${GIT_BRANCH}
- export USUL_INC_DIR=`pwd`/source
- mkdir build
- cd build
- cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DUSUL_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release" -DUSUL_ENABLE_CODE_COVERAGE=OFF
- cmake --build .
- cd ..
- rm -rf build
- mkdir build
- cd build
- cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DUSUL_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Debug" -DUSUL_ENABLE_CODE_COVERAGE=OFF
- cmake --build .

# Go back to the directory where we started.
- cd ${THIS_PROJECT_DIR}

# Now we can run our script.
- sh run_tests.sh
